// Generated by Finicky Kickstart
// Save as ~/.finicky.js

const workBrowser = {
  name: "Brave Browser",
  profile: "Work"
};

// com.brave.Browser.app.kjgfgldnnfoeklkmfkjfagphfepbbdan
const googleMeetApp = {
  browser: ({ urlString }) => ({
    ...workBrowser,
    args: [
      '--app-id=kjgfgldnnfoeklkmfkjfagphfepbbdan', // View application Info.plist for
      `--app-launch-url-for-shortcuts-menu-item=${ urlString }`,
    ],
  }),
};

export default {
  defaultBrowser: "Safari",
  handlers: [
	/*
    {
      // Open any link clicked in Slack in Safari
      match: ({ opener }) =>
        opener.bundleId === "com.tinyspeck.slackmacgap",
      browser: "Google Chrome"
    },
	*/
    /* Google Forms links */
    {
      match: finicky.matchHostnames(/forms\.gle/),
      browser: {
          name: "Brave Browser",
          profile: "Work",
      }
    },
    /* Google drive/docs/meet links */
    {
      match: finicky.matchHostnames(["meet.google.com"]),
      ...googleMeetApp,
    },
    {
      match: finicky.matchHostnames(/(notebooklm|docs|calendar|drive)\.google\.com/),
      browser: workBrowser
    },
    /* Anything .redhat.com */
    {
      match: /^https?:\/\/.*redhat\.com\/.*$/,
      browser: workBrowser
    },
    {
      match: /^https?:\/\/.*devshift\.net\/.*$/,
      browser: workBrowser
    },
    {
      match: /^https?:\/\/.*workday\.com\/.*$/,
      browser: workBrowser
    },
    {
      match: /^https?:\/\/.*redhat\.service-now\.com\/.*$/,
      browser: workBrowser
    },
    {
      match: /^https?:\/\/.*amplitude.com\/.*$/,
      browser: workBrowser
    },
    {
      match: /^https?:\/\/redhat.*\.lrn\.com\//,
      browser: workBrowser
    },
    {
      match: /^https?:\/\/.*redhat.*\.slack\.com\/.*$/,
      browser: workBrowser
    },
    {
      match: /^https?:\/\/.*redhat.*\.atlassian\.net\/.*$/,
      browser: workBrowser
    },
    {
      match: /^https?:\/\/.*online\.tableau\.com\/.*$/,
      browser: workBrowser
    },
    {
      match: /^https?:\/\/miro\.com\/.*$/,
      browser: workBrowser
    }
  ]
}
